export type LotStatus = 'available' | 'sold' | 'phase2' | 'ready' | 'commercial' | 'unavailable'

export interface Lot {
  id: string
  label: string
  status: LotStatus
  address?: string
  price?: number
  beds?: number
  baths?: number
  sqft?: number
  street?: string
}

export const LOT_STATUS_CONFIG: Record<LotStatus, { label: string; color: string; bg: string }> = {
  available:   { label: 'Available',        color: '#22c55e', bg: 'rgba(34,197,94,0.15)' },
  sold:        { label: 'Sold',             color: '#94a3b8', bg: 'rgba(148,163,184,0.15)' },
  phase2:      { label: 'Phase 2',          color: '#f97316', bg: 'rgba(249,115,22,0.15)' },
  ready:       { label: 'Ready to Develop', color: '#3b82f6', bg: 'rgba(59,130,246,0.15)' },
  commercial:  { label: 'Commercial',       color: '#8b5cf6', bg: 'rgba(139,92,246,0.15)' },
  unavailable: { label: 'Unavailable',      color: '#d1d5db', bg: 'rgba(209,213,219,0.15)' },
}

export const LOTS: Lot[] = [
  { id: 'lot-1',   label: '1',   status: 'sold',      street: 'Main' },
  { id: 'lot-2',   label: '2',   status: 'sold',      street: 'Main' },
  { id: 'lot-3',   label: '3',   status: 'sold',      street: 'Blind Creek Blvd' },
  { id: 'lot-4',   label: '4',   status: 'available', street: 'Blind Creek Blvd' },
  { id: 'lot-5',   label: '5',   status: 'sold',      street: 'Main' },
  { id: 'lot-6',   label: '6',   status: 'sold',      street: 'Main' },
  { id: 'lot-7',   label: '7',   status: 'available', street: 'Blackcurrant Court' },
  { id: 'lot-8',   label: '8',   status: 'available', street: 'Blackcurrant Court' },
  { id: 'lot-9',   label: '9',   status: 'ready',     street: 'Blackcurrant Court' },
  { id: 'lot-10',  label: '10',  status: 'sold',      street: 'Early Rose Bay' },
  { id: 'lot-11',  label: '11',  status: 'sold',      street: 'Early Rose Bay' },
  { id: 'lot-12',  label: '12',  status: 'sold',      street: 'Early Rose Bay' },
  { id: 'lot-13',  label: '13',  status: 'sold',      street: 'Early Rose Bay' },
  { id: 'lot-14',  label: '14',  status: 'available', street: 'Early Rose Bay' },
  { id: 'lot-15',  label: '15',  status: 'available', street: 'Early Rose Bay' },
  { id: 'lot-16',  label: '16',  status: 'sold',      street: 'Langill Way' },
  { id: 'lot-17',  label: '17',  status: 'sold',      street: 'Langill Way' },
  { id: 'lot-18',  label: '18',  status: 'sold',      street: 'Langill Way' },
  { id: 'lot-19',  label: '19',  status: 'available', street: 'Langill Way' },
  { id: 'lot-20',  label: '20',  status: 'available', street: 'Langill Way' },
  { id: 'lot-21',  label: '21',  status: 'available', street: 'Langill Way' },
  { id: 'lot-22',  label: '22',  status: 'sold',      street: 'Langill Way' },
  { id: 'lot-23',  label: '23',  status: 'sold',      street: 'Langill Way' },
  { id: 'lot-24',  label: '24',  status: 'sold',      street: 'Wild Plum Lane' },
  { id: 'lot-25',  label: '25',  status: 'sold',      street: 'Wild Plum Lane' },
  { id: 'lot-26',  label: '26',  status: 'available', street: 'Wild Plum Lane' },
  { id: 'lot-27',  label: '27',  status: 'sold',      street: 'Wild Plum Lane' },
  { id: 'lot-28',  label: '28',  status: 'phase2',    street: 'Wild Plum Lane', price: 494000, beds: 3, baths: 2, sqft: 1405 },
  { id: 'lot-29',  label: '29',  status: 'available', street: 'Wild Plum Lane' },
  { id: 'lot-30',  label: '30',  status: 'sold',      street: 'Wild Plum Lane' },
  { id: 'lot-31',  label: '31',  status: 'sold',      street: 'Wild Plum Lane' },
  { id: 'lot-32',  label: '32',  status: 'sold',      street: 'Wild Plum Lane' },
  { id: 'lot-33',  label: '33',  status: 'available', street: 'Woodland Drive' },
  { id: 'lot-34',  label: '34',  status: 'available', street: 'Woodland Drive' },
  { id: 'lot-35',  label: '35',  status: 'available', street: 'Woodland Drive' },
  { id: 'lot-36',  label: '36',  status: 'ready',     street: 'Woodland Drive' },
  { id: 'lot-37',  label: '37',  status: 'ready',     street: 'Woodland Drive' },
  { id: 'lot-38',  label: '38',  status: 'available', street: 'Woodland Drive' },
  { id: 'lot-39',  label: '39',  status: 'sold',      street: 'Woodland Drive', price: 494900, beds: 3, baths: 2, sqft: 1405 },
  { id: 'lot-40',  label: '40',  status: 'sold',      street: 'Woodland Drive' },
  { id: 'lot-41',  label: '41',  status: 'sold',      street: 'Woodland Drive' },
  { id: 'lot-42',  label: '42',  status: 'sold',      street: 'Woodland Drive' },
  { id: 'lot-43',  label: '43',  status: 'sold',      street: 'Woodland Drive' },
  { id: 'lot-44',  label: '44',  status: 'available', street: 'Woodland Drive' },
  { id: 'lot-45',  label: '45',  status: 'available', street: 'Woodland Drive' },
  { id: 'lot-46',  label: '46',  status: 'available', street: 'Woodland Drive' },
  { id: 'lot-47',  label: '47',  status: 'sold',      street: 'Woodland Drive' },
  { id: 'lot-48',  label: '48',  status: 'sold',      street: 'Woodland Drive' },
  { id: 'lot-49',  label: '49',  status: 'sold',      street: 'Woodland Drive' },
  { id: 'lot-50',  label: '50',  status: 'available', street: 'Woodland Drive' },
  { id: 'lot-51',  label: '51',  status: 'sold',      street: 'Wild Plum Lane' },
  { id: 'lot-52',  label: '52',  status: 'sold',      street: 'Wild Plum Lane' },
  { id: 'lot-53',  label: '53',  status: 'sold',      street: 'Wild Plum Lane' },
  { id: 'lot-54',  label: '54',  status: 'available', street: 'Wild Plum Lane' },
  { id: 'lot-55',  label: '55',  status: 'sold',      street: 'Wild Plum Lane' },
  { id: 'lot-56',  label: '56',  status: 'sold',      street: 'Park Road West' },
  { id: 'lot-57',  label: '57',  status: 'sold',      street: 'Park Road West' },
  { id: 'lot-58',  label: '58',  status: 'sold',      street: 'Park Road West' },
  { id: 'lot-59',  label: '59',  status: 'sold',      street: 'Park Road West' },
  { id: 'lot-60',  label: '60',  status: 'sold',      street: 'Park Road West' },
  { id: 'lot-61',  label: '61',  status: 'sold',      street: 'Park Road West' },
  { id: 'lot-62',  label: '62',  status: 'phase2',    street: 'Park Road West' },
  { id: 'lot-63',  label: '63',  status: 'phase2',    street: 'Langill Way' },
  { id: 'lot-64',  label: '64',  status: 'phase2',    street: 'Langill Way' },
  { id: 'lot-65',  label: '65',  status: 'phase2',    street: 'Langill Way' },
  { id: 'lot-66',  label: '66',  status: 'phase2',    street: 'Langill Way' },
  { id: 'lot-67',  label: '67',  status: 'phase2',    street: 'Langill Way' },
  { id: 'lot-68',  label: '68',  status: 'phase2',    street: 'Langill Way' },
  { id: 'lot-69',  label: '69',  status: 'available', street: 'Langill Way' },
  { id: 'lot-70',  label: '70',  status: 'available', street: 'Langill Way' },
  { id: 'lot-71',  label: '71',  status: 'available', street: 'Langill Way' },
  { id: 'lot-72',  label: '72',  status: 'available', street: 'Langill Way' },
  { id: 'lot-73',  label: '73',  status: 'sold',      street: 'Blackcurrant Court' },
  { id: 'lot-74',  label: '74',  status: 'sold',      street: 'Blackcurrant Court' },
  { id: 'lot-75',  label: '75',  status: 'sold',      street: 'Blackcurrant Court' },
  { id: 'lot-76',  label: '76',  status: 'available', street: 'Blackcurrant Court' },
  { id: 'lot-77',  label: '77',  status: 'available', street: 'Blackcurrant Court' },
  { id: 'lot-78',  label: '78',  status: 'available', street: 'Blackcurrant Court', price: 574900, beds: 3, baths: 3, sqft: 1920 },
  { id: 'lot-79',  label: '79',  status: 'sold',      street: 'Blackcurrant Court' },
  { id: 'lot-80',  label: '80',  status: 'sold',      street: 'Blackcurrant Court' },
  { id: 'lot-81',  label: '81',  status: 'sold',      street: 'Wild Plum Lane' },
  { id: 'lot-82',  label: '82',  status: 'sold',      street: 'Wild Plum Lane', price: 574900, beds: 3, baths: 3, sqft: 1920 },
  { id: 'lot-83',  label: '83',  status: 'sold',      street: 'Wild Plum Lane' },
  { id: 'lot-84',  label: '84',  status: 'sold',      street: 'Wild Plum Lane' },
  { id: 'lot-85',  label: '85',  status: 'available', street: 'Wild Plum Lane' },
  { id: 'lot-86',  label: '86',  status: 'available', street: 'Wild Plum Lane', price: 120000 },
  { id: 'lot-87',  label: '87',  status: 'available', street: 'Wild Plum Lane' },
  { id: 'lot-88',  label: '88',  status: 'sold',      street: 'Wild Plum Lane' },
  { id: 'lot-89',  label: '89',  status: 'sold',      street: 'Wild Plum Lane' },
  { id: 'lot-90',  label: '90',  status: 'sold',      street: 'Wild Plum Lane', price: 499900, beds: 3, baths: 2, sqft: 1405 },
  { id: 'lot-91',  label: '91',  status: 'sold',      street: 'Wild Plum Lane' },
  { id: 'lot-92',  label: '92',  status: 'sold',      street: 'Wild Plum Lane', price: 479900, beds: 3, baths: 2, sqft: 1403 },
  { id: 'lot-93',  label: '93',  status: 'sold',      street: 'Wild Plum Lane' },
  { id: 'lot-94',  label: '94',  status: 'sold',      street: 'Wild Plum Lane' },
  { id: 'lot-95',  label: '95',  status: 'sold',      street: 'Wild Plum Lane' },
  { id: 'lot-96',  label: '96',  status: 'sold',      street: 'Wild Plum Lane' },
  { id: 'lot-97',  label: '97',  status: 'sold',      street: 'Wild Plum Lane' },
  { id: 'lot-98',  label: '98',  status: 'sold',      street: 'Wild Plum Lane', price: 479900, beds: 3, baths: 2, sqft: 1403 },
  { id: 'lot-99',  label: '99',  status: 'sold',      street: 'Wild Plum Lane' },
  { id: 'lot-100', label: '100', status: 'available', street: 'Langill Way' },
  { id: 'lot-101', label: '101', status: 'sold',      street: 'Langill Way' },
  { id: 'lot-102', label: '102', status: 'sold',      street: 'Langill Way' },
  { id: 'lot-103', label: '103', status: 'sold',      street: 'Langill Way' },
  { id: 'lot-104', label: '104', status: 'sold',      street: 'Langill Way' },
  { id: 'lot-105', label: '105', status: 'sold',      street: 'Langill Way' },
  { id: 'lot-106', label: '106', status: 'available', street: 'Langill Way' },
  { id: 'lot-107', label: '107', status: 'available', street: 'Langill Way' },
  { id: 'lot-108', label: '108', status: 'available', street: 'Langill Way' },
  { id: 'lot-109', label: '109', status: 'sold',      street: 'Langill Way' },
  { id: 'lot-110', label: '110', status: 'sold',      street: 'Langill Way' },
  { id: 'lot-111', label: '111', status: 'sold',      street: 'Langill Way' },
  { id: 'lot-112', label: '112', status: 'sold',      street: 'Langill Way' },
  { id: 'lot-113', label: '113', status: 'sold',      street: 'Langill Way' },
  { id: 'lot-114', label: '114', status: 'sold',      street: 'Langill Way' },
  { id: 'lot-115', label: '115', status: 'sold',      street: 'Langill Way' },
  { id: 'lot-116', label: '116', status: 'sold',      street: 'Langill Way' },
  { id: 'lot-117', label: '117', status: 'sold',      street: 'Langill Way' },
  { id: 'lot-118', label: '118', status: 'sold',      street: 'Langill Way' },
  { id: 'lot-119', label: '119', status: 'sold',      street: 'Langill Way' },
  { id: 'lot-120', label: '120', status: 'available', street: 'Langill Way' },
  { id: 'lot-121', label: '121', status: 'available', street: 'Langill Way' },
  { id: 'lot-122', label: '122', status: 'phase2',    street: 'Langill Way' },
  { id: 'lot-123', label: '123', status: 'phase2',    street: 'Langill Way' },
  { id: 'lot-124', label: '124', status: 'phase2',    street: 'Langill Way' },
  { id: 'lot-125', label: '125', status: 'phase2',    street: 'Langill Way' },
  { id: 'lot-126', label: '126', status: 'phase2',    street: 'Langill Way' },
  { id: 'lot-127', label: '127', status: 'phase2',    street: 'Langill Way' },
]

export const LOT_MAP = Object.fromEntries(LOTS.map(l => [l.id, l]))
